language: java

addons:
  postgresql: "9.6"

cache:
  directories:
  - $HOME/.m2

before_script:
  - psql -c "CREATE DATABASE seqdb_api_test;" -U postgres
  - psql -f src/test/resources/create-test-users.sql -U postgres

script: 
  - mvn verify -Dspring.datasource.url=jdbc:postgresql://localhost/seqdb_api_test?currentSchema=seqdb -Dspring.datasource.username=test -Dspring.datasource.password=test -Dspring.liquibase.url=jdbc:postgresql://localhost/seqdb_api_test checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check jacoco:check

jdk:
  - openjdk8
  - openjdk10
  - openjdk11
