language: java

cache:
  directories:
  - $HOME/.m2

script: 
  - mvn verify checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check jacoco:check
 
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
