language: java

cache:
  directories:
  - $HOME/.m2

script: mvn install

jdk:
  - openjdk8
  - openjdk9
  - openjdk10

deploy:
  - provider: script
    script: bash docker-push-prod.sh
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: script
    script: bash docker-push-dev.sh
    skip_cleanup: true
    on:
      branch: dev
