language: java

cache:
  directories:
  - $HOME/.m2

script: 
  - mvn checkstyle:check
  - mvn com.github.spotbugs:spotbugs-maven-plugin:check
  - mvn verify
  
jdk:
  - openjdk8
  - openjdk9
  - openjdk10
