language: java

cache:
  directories:
  - $HOME/.m2

script: 
  - mvn install checkstyle:check com.github.spotbugs:spotbugs-maven-plugin:check

jdk:
  - openjdk8
  - openjdk10
  - openjdk11

deploy:
  - provider: script
    script: bash docker-push-prod.sh
    skip_cleanup: true
    on:
      branch: master
      tags: true
  - provider: script
    script: bash docker-push-dev.sh
    skip_cleanup: true
    on:
      branch: dev
