spring:
  jpa:
    properties.hibernate:
      # Ehcache enabled to improve Hibernate performance.
      cache:
        use_second_level_cache: true
        use_query_cache: true
        # Fixes "net.sf.ehcache.CacheException: Another unnamed CacheManager already exists" error
        # when testing 
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      naming:
        # Naming strategies specified to allow @Column/@Table name property.
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    