spring:
  datasource:
    url: jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1 ;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS seqdb
  jpa:
    properties.hibernate:
      # Ehcache enabled to improve Hibernate performance.
      cache:
        use_second_level_cache: true
        use_query_cache: true
        # Fixes "net.sf.ehcache.CacheException: Another unnamed CacheManager already exists" error
        # when testing 
        region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
      # The default schema is only compatible with postgres (not mysql)
      default_schema: seqdb
    hibernate:
      naming:
        # Naming strategies specified to allow @Column/@Table name property.
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    defaultSchema: seqdb
    # on existing database use "schema-change" only
    contexts: schema-change, initial-data
crnk:
  pathPrefix: /api
  domainName: ""
  defaultPageLimit: 20
  maxPageLimit: 1000
  allow-unknown-attributes: true

keycloak:
  # Disable Keycloak by default.
  enabled: false