spring:
  datasource:
    url:  jdbc:h2:mem:mydb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS seqdb\;SET SCHEMA seqdb
 #   url: jdbc:postgresql://localhost:5532/seqdb
 #   username: postgres
 #   password: postgres
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: schema-change, initial-data
    # Physical naming strategy specified to allow @Table name property.
  jpa:
    properties.jakarta.persistence.validation.mode: none
    open-in-view: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://keycloak-server/auth/realms/your-realm

# We shouldn't get "Request header is too large" errors:
server.max-http-header-size: 10MB

rabbitmq:
  queue: dina.search.queue
  username: guest
  password: guest
  host: ${RABBITMQ_HOSTNAME:localhost}

keycloak:
  enabled: false

logging:
  level:
    com.github.tennaito.rsql: ERROR
dina:
  auditing:
    enabled: true
  messaging:
    isProducer: false
  apiPrefix: /api

javers:
  packagesToScan: ca.gc.aafc.seqdb.api
  # Don't let Javers create its tables; let Liquibase create them:
  sqlSchemaManagementEnabled: false
