-- Revoke privileges for PUBLIC user
-- REVOKE CONNECT ON DATABASE seqdb_api_test FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS seqdb;
-- REVOKE CREATE ON SCHEMA seqdb FROM PUBLIC;

-- depends on the "seqdb" schema
CREATE ROLE test_migration NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE seqdb_api_test TO test_migration;
GRANT USAGE, CREATE ON SCHEMA seqdb TO test_migration;
ALTER DEFAULT PRIVILEGES IN SCHEMA seqdb GRANT ALL PRIVILEGES ON TABLES TO test_migration;
ALTER ROLE test_migration SET search_path = seqdb;

CREATE ROLE test_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE seqdb_api_test TO test_user;
GRANT USAGE ON SCHEMA seqdb TO test_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA seqdb TO test_user;
ALTER DEFAULT PRIVILEGES FOR USER test_migration IN SCHEMA seqdb GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO test_user;
