-- Revoke privileges for PUBLIC user
REVOKE CONNECT ON DATABASE seqdb_test FROM PUBLIC;
REVOKE USAGE, CREATE ON SCHEMA public FROM PUBLIC;
CREATE SCHEMA IF NOT EXISTS seqdb;
REVOKE CREATE ON SCHEMA seqdb FROM PUBLIC;

-- migration user
CREATE ROLE migration_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE seqdb_test TO migration_user;
GRANT USAGE, CREATE ON SCHEMA seqdb TO migration_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA seqdb GRANT ALL PRIVILEGES ON TABLES TO migration_user;

-- web user
CREATE ROLE web_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE seqdb_test TO web_user;
GRANT USAGE ON SCHEMA seqdb TO web_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA seqdb TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA seqdb GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA seqdb GRANT SELECT, USAGE ON SEQUENCES TO web_user;

-- Enable pgcrypto extension for UUID support:
CREATE EXTENSION IF NOT EXISTS "pgcrypto" SCHEMA seqdb;
