= Configuration

This application is configured using Spring Boot, with default properties stored in src/main/resources/application.yml. It can be link:https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html[configured externally using properties files, YAML files, environment variables, and command-line arguments].

* link:https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html[Common Spring properties]
* link:http://www.crnk.io/releases/stable/documentation/#_integration_with_spring_and_string_boot[Crnk properties]

* Importing Sample Accounts: When running the application locally with an in-memory or MySQL database it may be useful to have 2 existing Accounts that you can log into. To import the Admin (username=Admin, password=Admin) and User (username=User, password=User) accounts, set the configuration property "import-sample-accounts" to true. **Warning:** This is a dangerous argument to run on production because it will import an admin account with an easy password. You should only pass this argument from the command line or from an external configuration file that is only used on a local dev instance, instead of src/resources/application.yml.
