= Running the application

== Required

* Java 1.8+
* Maven 3.2+

== To launch

[source,bash]
----
mvn clean spring-boot:run
----

== To run test

Unit tests:

[source,bash]
----
mvn clean test
----

All tests (Integration + Unit):

[source,bash]
----
mvn clean verify
----

== To package

[source,bash]
----
mvn clean install
----

This will create an executable jar.

== To run the packaged application (using an embedded Tomcat instance)

[source,bash]
----
java -jar seqdb.api.jar
----

You can also include configuration from an external file:

[source,bash]
----
java -jar seqdb.api.jar --spring.config.additional-location=./myconfig.yml
----

== Generate Maven reports

* Checkstyle
* SpotBugs
* OWASP dependency-check
* Jacoco

[source,bash]
----
mvn clean verify site
----

== Run Liquibase exlusively

* Make sure the liquibase.properties file has the required parameters for the target environment, default is provided in the project, under /src/main/resources
* Make sure seqdb.api-versionNumber.jar file is available at classpath
* At project folder, such as seqdb-api, run mvn liquibase-update, this should regenerate the database based on the changelogs provided in above jar file
 

[source,bash]
----
cd seqdb-api
mvn liquibase:update
----
