= Using the REST API

This application provides a REST API that conforms to the https://jsonapi.org/[JSON:API] specification. 

== Home endpoint

There is a "Home" endpoint at /api , which lists the available repositories.

== Meta information

You can access metadata about available repositories, resources, attributes, etc. at /api/meta/ .
This information is generated by https://www.crnk.io/releases/stable/documentation/#_meta_module[Crnk's Meta Module].

== Sparse field selection

You can limit which fields are included in a response using the fields.

Listing regions with "name" and "description" as the only included fields:

----
/api/region?fields[region]=name,description
----

== Filtering

Listing pcrPrimers where the name is "101F":

----
/api/pcrPrimer?filter[name]=101F
----

== Pagination

You can paginate list data using "page[limit]" and "page[offset]" parameters.

The first page of regions with a page size of 100:

----
/api/region?page[limit]=100
----

The second page:

----
/api/region?page[limit]=100&page[offset]=100
----

The third page:

----
/api/region?page[limit]=100&page[offset]=200
----

== Sorting

You can sort listed data in ascending or descending order, and specify multiple sort fields.

Sorting regions by name (ascending):

----
/api/region?sort=name
----

Sorting regions by name (descending):

----
/api/region?sort=-name
----

Sorting regions by name (ascending) and description (descending when multiple regions have the same name):

----
/api/region?sort=name,-description
----

== Creating a resource

Creating a new Region:

[source,bash]
----
curl -XPOST -H "Content-Type: application/vnd.api+json" \
--data '{"data":{"type": "region", "attributes": {"name":"My Region", "description":"My Description", "symbol":"My Symbol"}}}' \
http://localhost:8080/api/region
----
