= Using the REST API

This application provides a REST API that conforms to the https://jsonapi.org/[JSON:API] specification. 

== Home endpoint

There is a "Home" endpoint at /api , which lists the available repositories.

== Meta information

You can access metadata about available repositories, resources, attributes, etc. at /api/meta/ .
This information is generated by https://www.crnk.io/releases/stable/documentation/#_meta_module[Crnk's Meta Module].

== Sparse field selection

You can limit which fields are included in a response using the fields.

Listing regions with "name" and "description" as the only included fields:

----
/api/region?fields[region]=name,description
----

== Filtering

=== Simple key-value filter

----
localhost:8080/api/region?filter[name]=ITS&filter[description]=Internal%20Transcribed%20Spacer
----

returns:

----
{
    "data": [
        {
            "id": "43",
            "type": "region",
            "attributes": {
                "symbol": "ITS",
                "name": "ITS",
                "description": "Internal Transcribed Spacer"
            },
            "links": {
                "self": "/api/region/43"
            }
        }
    ]
}
----


=== RSQL

seqdb-api supports https://github.com/jirutka/rsql-parser[RSQL (REST query language)] for more complex filter queries.

----
localhost:8080/api/region?filter[rsql]=( name=='12S' or name=='142' )
----

returns

----
{
    "data": [
        {
            "id": "142",
            "type": "region",
            "attributes": {
                "symbol": "142",
                "name": "142",
                "description": ""
            },
            "links": {
                "self": "/api/region/142"
            }
        },
        {
            "id": "284",
            "type": "region",
            "attributes": {
                "symbol": "12S",
                "name": "12S",
                "description": "mitochondrial"
            },
            "links": {
                "self": "/api/region/284"
            }
        },
        {
            "id": "366",
            "type": "region",
            "attributes": {
                "symbol": "12S",
                "name": "12S",
                "description": null
            },
            "links": {
                "self": "/api/region/366"
            }
        }
    ]
}
----

== Pagination

You can paginate list data using "page[limit]" and "page[offset]" parameters.

The first page of regions with a page size of 100:

----
/api/region?page[limit]=100
----

The second page:

----
/api/region?page[limit]=100&page[offset]=100
----

The third page:

----
/api/region?page[limit]=100&page[offset]=200
----

== Sorting

You can sort listed data in ascending or descending order, and specify multiple sort fields.

Sorting regions by name (ascending):

----
/api/region?sort=name
----

Sorting regions by name (descending):

----
/api/region?sort=-name
----

Sorting regions by name (ascending) and description (descending when multiple regions have the same name):

----
/api/region?sort=name,-description
----

== Creating a resource

Creating a new Region:

[source,bash]
----
curl -XPOST -H "Content-Type: application/vnd.api+json" \
--data '{"data":{"type": "region", "attributes": {"name":"My Region", "description":"My Description", "symbol":"My Symbol"}}}' \
http://localhost:8080/api/region
----
